version: 1.0
games-settings:
  example:
    name: 'Example image'
    generator:
      initial-number-of-rooms: 70
      percentage-of-additional-edges: 20
      building-style: # ID всех блоков: https://minecraft-inside.ru/blocks/1.18.2/
        floor: 'birch_planks'
        baseboard: 'acacia_planks'
        wall: 'oak_planks'
        ceiling: 'spruce_planks'
        light: 'glowstone'
